# Generated by Django 2.2.2 on 2024-09-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_App', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
