# Generated by Django 2.2.2 on 2024-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_App', '0005_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=255)),
                ('Cnumber', models.CharField(max_length=255)),
                ('Cemail', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
