# Generated by Django 2.2.2 on 2024-09-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_App', '0006_auto_20240916_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
